### ISSUE TITLE
tempbow variable declaration

### ISSUE THREAD

**Issue by zapatalab** [mrmckain/Fast-Plast#15]
In line 1084 of `fast-plast.pl` the variable `tempbow` needs to be declared with `$` instead of `@`

**Comment by mrmckain** [comment]
Fixed the error. It isn't that @tempbow needs to be declared as $ but needs to be called as an array later.

**Comment by zapatalab** [comment]
Great. Sorry, totally a perl-ignorant here trying to fix perl code ;-)
