### ISSUE TITLE
Error with "--skip trim"

### ISSUE THREAD

**Issue by dfmoralesb** [mrmckain/Fast-Plast#16]
Hi Michael,

When using the the option "--skip trim" the error below is produced. I check my input files and that's not the problem. When using the same input files and removing the "--skip trim" option there is no problem, but all my input files were trimmed from previous from previous analyses, so I find that option useful. 

Thanks,
Diego

Building a SMALL index
Error: reads file does not look like a FASTQ file
terminate called after throwing an instance of 'int'
Aborted
(ERR): bowtie2-align exited with value 134
No mapped reads files were identified to run SPAdes.  Please check 2_Bowtie_Mapping.

**Comment by mrmckain** [comment]
Hi Diego,

I just saw this; sorry about the delay. 

I just ran a test and things are working OK for me. Can you answer these question to help me figure out what might be going on with your run?

1) Are your files FASTQ? 
2) Did you use the full path for the read files?

Here is my call for a run.  In this case, I used previously trimmed reads from another Fast-Plast run:

 perl /mrm/bin/Fast-Plast/fast-plast.pl -1 /mrm/Vaccinium/Vaccinium_ovatum-72454-ERIConly/1_Trimmed_Reads/Vaccinium_ovatum-72454-ERIConly.trimmed_P1.fq -2 /mrm/Vaccinium/Vaccinium_ovatum-72454-ERIConly/1_Trimmed_Reads/Vaccinium_ovatum-72454-ERIConly.trimmed_P2.fq --name Vaccinium_ovatum-72454-ERIConly-skiptrim --bowtie_index Ericaceae --coverage_analysis --skip trim --clean light

**Comment by dfmoralesb** [comment]
Hi Michael,

Yes, to your two questions. I tried different calls and this is what I got.

gzipped input files without "--coverage_analysis" option  - error (this was my original call)
gzipped input files with "--coverage_analysis" option  - error
uncompress input files without "--coverage_analysis" option  - error
uncompress input files with "--coverage_analysis" option  - works (as in your example)

Thanks,
Diego

**Comment by mrmckain** [comment]
The gzipped issues, I believe, are due to bowtie2 not accepting gzipped files.  I added some code that will detect if pretrimmed files are gzipped and uncompress them. 

Can you send me more info on the  "uncompress input files without "--coverage_analysis" option - error" error?  What do the log and error log say? You can email them to me if that is easier.

Michael

**Comment by dfmoralesb** [comment]
The error was the same as the original one, but I run it again today the "uncompress input files without "--coverage_analysis" call and it worked. The error was only with thee gzipped files. I must called it "error" by mistake.

Thanks,
Diego

**Comment by mrmckain** [comment]
Great!  That makes more sense.  Does the new code work for you with compressed files?

**Comment by dfmoralesb** [comment]
No, I got this error:

sh: 1: Syntax error: "(" unexpected
sh: 1: Syntax error: "(" unexpected
Building a SMALL index
No trimmed read files were identified to run SPAdes.  Please check 1_Trimmed_Reads.

**Comment by mrmckain** [comment]
I am trying to go through past issues to tie up loose ends. I think I had pushed a new fix for this. Did you get it working?

**Comment by dfmoralesb** [comment]
Yes, it did work.

Diego
