### ISSUE TITLE
Global symbol "$TRIMMOMATIC" requires explicit package name

### ISSUE THREAD

**Issue by scrameri** [mrmckain/Fast-Plast#20]
Dear Michael,

I was looking for such a pipeline for a long time, and your program looks great, thank you very much!

However, I kept getting errors of this kind when starting fast-plast:

> Global symbol "$TRIMMOMATIC" requires explicit package name at ~/bin/Fast-Plast/fast-plast.pl line 257.> 

There might be a misspelled "TRIMMOMATIC" variable definition in the newest fast-plast.pl script. By looking at the script, I found this at line 25:

`
grep -n 'my $TRMIMMOMATIC="' ~/bin/Fast-Plast/fast-plast.pl
`
> 25:my $TRMIMMOMATIC="/usr/local/trimmomatic/trimmomatic-0.32.jar"; #path to trimmomatic executable>

Probably the error occurs because the variable actually set is called "TRMIMMOMATIC" instead of "TRIMMOMATIC", right?

Best wishes,
Simon

**Comment by scrameri** [comment]
Hi Michael, 

checked again: the initial fast-plast.pl script looks ok. Interestingly, the $TRIMMOMATIC variable gets changed to $TRMIMMOMATIC after installing it using my path to trimmomatic executable, which is "/usr/local/trimmomatic/"

I did not set the path by hand, but did it using the INSTALL.pl script. The change seems to occur during the INSTALL.pl

Maybe there is some regex issue?

UPDATE:
found the likely error in the INSTALL.pl script, line 508:

`grep -n 'TRMIMMOMATIC' INSTALL.pl`

>508:            $tempf =~ s/my \$TRIMMOMATIC\;/my \$TRMIMMOMATIC=\"$trimmomatic\"\;/;>


If I correct the variable definition in fast-plast.pl manually, the program runs smoothly.

**Comment by mrmckain** [comment]
Thanks for pointing this out!  I fixed it on the master.
