### ISSUE TITLE
hang in Afin stage

### ISSUE THREAD

**Issue by fayweili** [mrmckain/Fast-Plast#28]
Hello! My run has been stuck in the Afin stage after "_afin_iter1.fa" file was produced. The last few lines in "_afin.log": 

0:22:34	Begin Extensions 
0:23:15	Fuse contigs
0:23:35	Begin Extensions
0:23:58	Fuse contigs

**Comment by mrmckain** [comment]
Sorry for the delay. I missed my alerts to issues on here.

Do you mean it stop running? Did it freeze? I have never had this error, so I am not sure what is going on. What do your error logs say? 

Thanks,
Michael
