### ISSUE TITLE
Directory issues 

### ISSUE THREAD

**Issue by mariamariamaria123** [mrmckain/Fast-Plast#31]
This is the error I get when I run the program:

Can't exec "/nv/hp16/mahmad42/ncbi-blast-2.2.29+/bin/blastn/makeblastdb": Not a directory at /nv/hp16/mahmad42/filefile/Fast-Plast-master/fast-plast.pl line 1692.
sh: /nv/hp16/mahmad42/ncbi-blast-2.2.29+/bin/blastnblastn: No such file or directory
Can't exec "/nv/hp16/mahmad42/ncbi-blast-2.2.29+/bin/blastn/makeblastdb": Not a directory at /nv/hp16/mahmad42/filefile/Fast-Plast-master/fast-plast.pl line 1409, <$cpdbgenes> line 26526.
sh: /nv/hp16/mahmad42/ncbi-blast-2.2.29+/bin/blastnblastn: No such file or directory
Died at /nv/hp16/mahmad42/filefile/Fast-Plast-master/fast-plast.pl line 876.

It appears it cannot find a certain directory? Is this an issue in the fast-plast.pl script?

**Comment by mrmckain** [comment]
Sorry for the delay. I missed these issues.

This appears to be an issue in where Fast-Plast is being told BLAST is.  Can you check the beginning of the fastplast.pl file to make sure things are set properly?

Best,
Michael
