### ISSUE TITLE
issue with bowtie completing

### ISSUE THREAD

**Issue by angelajmcd** [mrmckain/Fast-Plast#32]
Hi Michael,

I've been trying to assemble some plastomes with Fast-Plast today but haven't been able to get past step 2. I installed it via your instructions, with all the dependencies in the bin folder. I've also verified that fast-plast.pl paths to dependency directories are also set (though they could be wrong, I suppose. I'll paste them here:
###directories
my $FPROOT = "$FindBin::RealBin";
my $AFIN_DIR = "$FPROOT/afin";
my $COVERAGE_DIR = "$FPROOT/Coverage_Analysis";
my $FPBIN = "$FPROOT/bin";
my $TRIMMOMATIC="/Applications/Fast-Plast/bin/Trimmomatic-0.36//trimmomatic-0.36.jar"; #path to trimmomatic executable
my $BOWTIE2="/Applications/Fast-Plast/bin/bowtie2-2.2.9/bowtie2"; #path to bowtie2 executable
my $SPADES="/Applications/Fast-Plast/bin/SPAdes-3.11.1-Linux/bin/spades.py"; #path to spades executable
my $BLAST="/Applications/Fast-Plast/bin/ncbi-blast-2.6.0+/bin/"; #path to blast executable
my $SSPACE="/Applications/Fast-Plast/bin/sspace_basic-2.1.1//SSPACE_Basic.pl"; #path to sspace exectuable
my $BOWTIE1="/Applications/Fast-Plast/bin/bowtie-1.1.2/"; #path to bowtie1 executable
my $JELLYFISH="/Applications/Fast-Plast/bin/jellyfish-2.2.6/bin/jellyfish"; #path to jellyfish2 excecutable

Anyway. The error I get looks like this (after trimmomatic completes successfully):
Use of uninitialized value $temp_order in exists at fast-plast.pl line 1130, <$default_gb> line 2041.
Use of uninitialized value $temp_order in hash element at fast-plast.pl line 1132, <$default_gb> line 2041.
Traceback (most recent call last):
  File "/Applications/Fast-Plast/bin/bowtie2-2.2.9/bowtie2-build", line 95, in <module>
    main()
  File "/Applications/Fast-Plast/bin/bowtie2-2.2.9/bowtie2-build", line 92, in main
    os.execv(build_bin_spec, argv)
OSError: [Errno 8] Exec format error
sh: /Applications/Fast-Plast/bin/bowtie2-2.2.9/bowtie2-align-s: cannot execute binary file
(ERR): Description of arguments failed!
Exiting now ...
No mapped reads files were identified to run SPAdes.  Please check 2_Bowtie_Mapping.

I've tried manually setting the paths to executables, letting the install script set paths, used zipped and unzipped reads, used options for --coverage_analysis and not, set full paths to reads and included reads in the folder with the script... I'm hoping I just am (repeatedly) making a silly error. 

Thoughts on what I might be doing wrong? 
Thanks a ton,
Angela

**Comment by mrmckain** [comment]
Hi Angela,

Are you running with a specific order for the mapping? If not, Fast-Plast is using each represented order in the database. One entry had an order missing, which is why you see the error at 1130/1132. That might be throwing the bowtie2 error. I have updated the GenBank_Plastomes file in bin to fix this.

Implement that new file and give it a go. Let me know how things progress.

Best,
Michael

**Comment by angelajmcd** [comment]
Hi Michael,
I tried it using Gentianales originally, but then I switched to using all orders. Both tries had the same result/errors. I updated this morning and have tried running with all orders and am getting stuck the same point. The lines about line 1130/1132 are gone but I get this now after TrimmomaticPE completes:
Traceback (most recent call last):
  File "/Applications/Fast-Plast/bin/bowtie2-2.2.9/bowtie2-build", line 95, in <module>
    main()
  File "/Applications/Fast-Plast/bin/bowtie2-2.2.9/bowtie2-build", line 92, in main
    os.execv(build_bin_spec, argv)
OSError: [Errno 8] Exec format error
sh: /Applications/Fast-Plast/bin/bowtie2-2.2.9/bowtie2-align-s: cannot execute binary file
(ERR): Description of arguments failed!
Exiting now ...
No mapped reads files were identified to run SPAdes.  Please check 2_Bowtie_Mapping.

Perhaps its a problem with how bowtie2 installs? I can't really tell.

**Comment by mrmckain** [comment]
Are you running on a Linux system? Mac's have a different Bowtie2 installation.

**Comment by angelajmcd** [comment]
Wow. I am not... :) 

I installed proper dependencies and edited the .pl file. It's runnin! Sorry & thanks!
