### ISSUE TITLE
Afin installation

### ISSUE THREAD

**Issue by carol-siniscalchi** [mrmckain/Fast-Plast#34]
Hey Mike,

I'm trying to run Fast-Plast in a ubuntu machine and I'm getting the following error when installing Afin:

carol@jmandel-OptiPlex-7010:~/Fast-Plast/afin$ make
g++ -std=c++11 -g -pthread -c afin.cpp -o afin.o 
cc1plus: error: unrecognized command line option ‘-std=c++11’
make: *** [afin.o] Error 1

The automatic installation using the INSTALL script also failed. I have zlib installed. 

Do you know what might be causing it? I tried to run some files and it stops right after the Spades step. 

Thanks!

**Comment by mrmckain** [comment]
Do you have a c++11 supported c++ compiler? For example, we use gcc5.4.0.

**Comment by mrmckain** [comment]
Is it in your path?
