### ISSUE TITLE
Utilizing --user_bowtie

### ISSUE THREAD

**Issue by nsmt89** [mrmckain/Fast-Plast#42]
Hi,
I want to use --user_bowtie function but I can't seem to successfully put it in command line. Do I need to specify the path? If I do, how to put it in the command line?

Thank you

**Comment by mrmckain** [comment]
For that option, you need to create the bowtie indices yourself and then give the option the path to the base name you used. For example, if you use a file call mysequence.fasta to make the bowtie indices and the file is in a place called /usr/mybin, then you would need to give the option the entry /usr/mybin/mysequence.fasta . This assumes that your bowtie indices are in the same directory as your sequences and that you didn't use a different base name. If you did, change accordingly.
