### ISSUE TITLE
Issues about bowtie2

### ISSUE THREAD

**Issue by jeniferclopes** [mrmckain/Fast-Plast#45]
I am trying to run FastPlast but I got stuck here: 

Can't exec "/home/geninfo/jdantas/Fast-Plast/bin/bowtie2-2.3.5.1/bowtie2-build": No such file or directory at fast-plast.pl line
 1169.
Can't exec "/home/geninfo/jdantas/Fast-Plast/bin/bowtie2-2.3.5.1/bowtie2": No such file or directory at fast-plast.pl line 593.
No mapped reads files were identified to run SPAdes.  Please check 2_Bowtie_Mapping.

How can I fix these issues? I followed the installation walkthrough.

Thanks

**Comment by mrmckain** [comment]
This suggests that you don't have bowtie installed where Fast-Plast is checking. Is this the correct path: /home/geninfo/jdantas/Fast-Plast/bin/bowtie2-2.3.5.1/bowtie2-build? If so, do you have access to it?

**Comment by jeniferclopes** [comment]
Thanks for your reply! We have solved the problem. The INSTALL.pl script
named the folder where Bowtie was installed with a different name used by
the fast-plast.pl script to call Bowtie. The problem was in the PATH.

Best Regards, Jenifer

Jenifer de Carvalho Lopes


Em qui., 9 de abr. de 2020 às 14:18, Michael McKain <
notifications@github.com> escreveu:

**Comment by mrmckain** [comment]
Great to hear.
