### ISSUE TITLE
Fast-Plast finished with only two directories (1_Trimmed_Reads and 2_Bowtie_Mapping)

### ISSUE THREAD

**Issue by MdkYTky** [mrmckain/Fast-Plast#46]
Now, I'm trying to assemble the chloroplast genome of a diatom with Fast-Plast (v.1.2.8).
This is the command that I tried.

`perl fast-plast.pl -1 L2_1.fq -2 L2_2.fq -n FastPlast --bowtie_index all --coverage_analysis --clean light --threads 8`

But, at the end of this command, i got only two directories (1_Trimmed_Reads and 2_Bowtie_Mapping).
Other files including log file were removed.

I can not understand what is happen...

**Comment by mrmckain** [comment]
Can you send the log, error, and other output files that track progress?

**Comment by MdkYTky** [comment]
Thank you for replying this issue.
I would like to send some files, but I don't have those files (They were removed at the end of above command).
Sorry, I'm very new for bioinfomatics, so if I have something to do, please let me know.

**Comment by mrmckain** [comment]
There should be some files produced with this naming format:

name_Fast-Plast_Progress.log
name_result_out.log
name__results_error.log

These are made early on and there is no automatic way that Fast-Plast removes them. They will say what errors there might be. Based on what you have described, my guess is either it is not installed properly (I would need some sort of error information to help with this) or there is a problem with your data. You should check to see if files are in the trimming directory. If so, move on to the bowtie2 directory to see what was produced. 

If you are running this on a scheduler, then there should be some report that comes back if there were problems from the scheduler. It is difficult to help without more information.

**Comment by mrmckain** [comment]
I just did a clean install to see if there were issues. I found one in the way bowtie2 was installed by the installation script. If you redownload and try again, I think it will work. At least, that will get you over a hurdle.

Best,
Michael

**Comment by MdkYTky** [comment]
Thank you for your kindness.
Following your advice, I redownloaded and set bowtie2 path, then it worked.
Thank you so much.
On Jul 22, 2020 06:55 +0900, Michael McKain <notifications@github.com>, wrote:

I just did a clean install to see if there were issues. I found one in the way bowtie2 was installed by the installation script. If you redownload and try again, I think it will work. At least, that will get you over a hurdle.

Best,
Michael

**Comment by jvalenciad** [comment]
Hi!
I have the same issue. I downloaded the installation script today, and there's maybe something wrong with SPADES. The file names in the Bowtie folder do have the sample name (and they look ok), but SPADES is not recognizing them in the next step.

This is the _Progress_log:

Mon Aug 10 15:15:09 2020        Starting Fast-Plast v.1.2.8.
                                Assemblying plastome with 0 single end libraries and 1 paired end libraries.
Mon Aug 10 15:15:09 2020        Determining best kmer sizes.
                                K-mer sizes for SPAdes set at 55,87,121.
Mon Aug 10 15:15:09 2020        Starting read trimming with Trimmomatic.
                                Using /scratch/.../Fast-Plast/bin/Trimmomatic-0.39//trimmomatic-0.39.jar.
Mon Aug 10 15:15:23 2020        Starting read mapping with bowtie2.
                                Using /scratch/.../Fast-Plast/bin/bowtie2-2.3.5.1-linux-x86_64/bowtie2.
                                Samples for Asparagales used to make bowtie2 indices.
                ******************ERROR: No trimmed read files were identified to run SPAdes.  Please check 1_Trimmed_Reads.******************

For clarity, these are the files in 1_Trimmed_Reads:
subset_file1.fq      subset_file2.fq

And these are the files in 2_Bowtie_Mapping:
Asparagales.fsa     V_lillacina_W3730_bowtie.2.bt2       V_lillacina_W3730_bowtie.4.bt2      V_lillacina_W3730_bowtie.rev.2.bt2
V_lillacina_W3730_bowtie.1.bt2        V_lillacina_W3730_bowtie.3.bt2        V_lillacina_W3730_bowtie.rev.1.bt2

Any clues of what to do?
Thank you.
Janice

**Comment by mrmckain** [comment]
Hi Janice,

Are you running this on a linux machine? The installation is for linux only. 

There should be trimmed files in the 1_Trimmed_Reads directory. Since there isn't, that suggests Trimmomatic isn't running properly. Do you have java installed?

Can you give me the log, out, and error files? 

Best,
Michael

**Comment by jvalenciad** [comment]
Hi Michael

I'm running it in a Linux machine, a HPC. You are right! I don't have java installed there... I have a conda with java and Trimmomatic in my HPC account, so I can install all other FastPlast dependencies there... I'm just not quite sure how to connect the Trimmomatic with the java in the pipeline... The other option is to provide the trimmed files (from the Trimmomatic in conda) to the pipeline and start in the Bowtie step... but I'm not quite sure how to do it either. Any advice? 

I'm attaching the log files, JIC

Thank you
Janice

[Vanda_lillacina_W3730_Fast-Plast_Progress.log](https://github.com/mrmckain/Fast-Plast/files/5059245/Vanda_lillacina_W3730_Fast-Plast_Progress.log)
[Vanda_lillacina_W3730_results_error.log](https://github.com/mrmckain/Fast-Plast/files/5059246/Vanda_lillacina_W3730_results_error.log)
[Vanda_lillacina_W3730_results_out.log](https://github.com/mrmckain/Fast-Plast/files/5059247/Vanda_lillacina_W3730_results_out.log)

**Comment by mrmckain** [comment]
Prior to running Fast-Plast, load conda with Trimmomatic (assuming it is a module). You can go to the fast-plast.pl script and change line 25 to give the path to wherever Trimmomatic is installed on your HPC.

To skip trimming, provide the trimmed R1 and R2 files to -1 and -2. Add the --skip trim flag when you run Fast-Plast.

**Comment by jvalenciad** [comment]
Thank you, Michael. 
The second option sounds easier for me :)
j.
