### ISSUE TITLE
Suggestion to Improve Assembly

### ISSUE THREAD

**Issue by nsmt89** [mrmckain/Fast-Plast#47]
[Cryptocoryne_nurii_1_Fast-Plast_Progress.log](https://github.com/mrmckain/Fast-Plast/files/5326044/Cryptocoryne_nurii_1_Fast-Plast_Progress.log)
Hi,
do you have any suggestion on improving towards completing this assembly?

Thank you

**Comment by mrmckain** [comment]
Could you sent me the other output files? Not the assembly but the other error/out files?  

Thanks!

**Comment by nsmt89** [comment]
[Cryptocoryne_nurii_1_results_out.log](https://github.com/mrmckain/Fast-Plast/files/5330959/Cryptocoryne_nurii_1_results_out.log)
[Cryptocoryne_nurii_1_results_error.log](https://github.com/mrmckain/Fast-Plast/files/5330961/Cryptocoryne_nurii_1_results_error.log)
[Cryptocoryne_nurii_1_results_out.log](https://github.com/mrmckain/Fast-Plast/files/5330962/Cryptocoryne_nurii_1_results_out.log)
Hi, I hope these are the files that you requested. 

Thanks

**Comment by mrmckain** [comment]
Looking over these files, I might suggest using the option to reduce the total number of reds to ~2 million. Sometimes having too high of coverage causes the pipeline to keep breaks in the assembly.

**Comment by nsmt89** [comment]
Is it by using --subsample option? If it is, where should I put it in the command line?

**Comment by mrmckain** [comment]
Anywhere is fine. All options have a specific ID, so order doesn't matter.
